"""
Typo / formatting robustness backtest for the patient-text extraction pipeline.

For every labelled case and every perturbation (perturb.py) it compares three things: the expected answer, the
prediction on the clean text, and the prediction on the corrupted text. Only regressions the corruption CAUSED are
counted (right on clean, wrong after), so existing errors do not blur the result.

  lost_symptom   a symptom that was correctly found on clean text and is missing after (silent false negative)
  gained_symptom a symptom not expected and not found on clean text, but asserted after (false positive; the
                 dangerous case is a lost negation: "I dont have fever" -> fever)
  lost_sign / gained_sign   the same for the danger-sign candidates (cannot_drink, convulsions, bleeding)
  broken_<field> patientType / durationDays / hydrationIssue right on clean text, wrong after

For each lost symptom it also records WHY (decision reasons from the pipeline): `not_mentioned` means the
exact-wording regex gate rejected it; `rescuable` counts the lost symptoms where the classifier itself still scored
above its threshold, i.e. a typo-tolerant gate could have kept them.

Usage (from the repo root, with ml/requirements.txt installed):
  python ml/robustness/backtest.py --artifact ml/artifacts/experimental_health_ie_final.joblib
Datasets: authored_dev (baseline + expanded diagnostics, 90 cases), authored_frozen (the frozen acceptance set,
48 cases; read-only, never tune against it), synthetic_test (190 template cases, if the split manifest exists).
"""

import argparse
import collections
import json
import random
import sys
from pathlib import Path

import joblib
from threadpoolctl import threadpool_limits

HERE = Path(__file__).resolve().parent
ML = HERE.parent
sys.path.insert(0, str(ML / "src"))
sys.path.insert(0, str(HERE))

from extraction_pipeline import ExtractionPipeline  # noqa: E402
from perturb import PERTURBATIONS, Ctx  # noqa: E402

SCALARS = ("patientType", "durationDays", "hydrationIssue")
MAX_EXAMPLES = 6


def load_datasets(include_synthetic: bool) -> dict[str, list[dict]]:
    def cases(name):
        return json.loads((ML / "data/evaluation" / name).read_text(encoding="utf-8"))["cases"]

    data = {
        "authored_dev": cases("baseline_diagnostics.json") + cases("expanded_diagnostics.json"),
        "authored_frozen": cases("frozen_acceptance_v1.json"),
    }
    if include_synthetic:
        try:
            from evaluate_improvements import raw_rows
            from prepare_baseline_data import prepare

            parts, _ = prepare()
            data["synthetic_test"] = raw_rows(parts["test"])
        except Exception as exc:  # the split manifest is generated by training; skip quietly if absent
            print(f"[skip] synthetic_test unavailable: {type(exc).__name__}: {exc}", file=sys.stderr)
    return data


def evidence_spans(result: dict) -> list[dict]:
    spans = []
    for key, value in result["evidence"].items():
        if key.startswith(("symptoms.", "reportedSigns.")):
            spans.extend(value)
    return spans


def blank() -> dict:
    return collections.defaultdict(int)


def run_one(pipe, case, name, fn, seed, clean, counts, examples):
    rng = random.Random(f"{name}:{case['id']}:{seed}")
    new_text = fn(case["text"], Ctx(rng=rng, spans=evidence_spans(clean)))
    if new_text == case["text"]:
        counts["noop"] += 1
        return
    pert = pipe.extract(new_text, case.get("target_subject"))
    exp = case["expected"]
    counts["applied"] += 1

    s_e, s_c, s_p = set(exp["symptoms"]), set(clean["symptoms"]), set(pert["symptoms"])
    g_e, g_c, g_p = set(exp["reportedSigns"]), set(clean["reportedSigns"]), set(pert["reportedSigns"])
    lost_sym, gained_sym = (s_c & s_e) - s_p, s_p - s_e - s_c
    lost_sign, gained_sign = (g_c & g_e) - g_p, g_p - g_e - g_c
    counts["symptom_opportunities"] += len(s_c & s_e)
    counts["sign_opportunities"] += len(g_c & g_e)
    counts["lost_symptom"] += len(lost_sym)
    counts["gained_symptom"] += len(gained_sym)
    counts["lost_sign"] += len(lost_sign)
    counts["gained_sign"] += len(gained_sign)
    counts["cases_with_symptom_change"] += bool(lost_sym or gained_sym)
    if s_c == s_e and s_p != s_e:
        counts["exact_set_broken"] += 1
    if s_c == s_e:
        counts["exact_set_opportunities"] += 1

    for label in lost_sym:
        d = pert["symptomDecisions"][label]
        counts["lost_not_mentioned"] += "not_mentioned" in d["reasons"]
        counts["lost_below_threshold"] += "below_threshold" in d["reasons"]
        counts["lost_rescuable"] += d["score"] >= d["threshold"]
    for field in SCALARS:
        if clean[field] == exp[field]:
            counts[f"{field}_opportunities"] += 1
            counts[f"{field}_broken"] += pert[field] != exp[field]

    if (lost_sym or gained_sym or lost_sign or gained_sign) and len(examples) < MAX_EXAMPLES:
        examples.append({
            "id": case["id"], "category": case.get("category", "synthetic"), "text": case["text"],
            "perturbed": new_text, "expected_symptoms": sorted(s_e), "clean_symptoms": sorted(s_c),
            "perturbed_symptoms": sorted(s_p), "expected_signs": sorted(g_e), "perturbed_signs": sorted(g_p),
            "lost_symptoms": sorted(lost_sym), "gained_symptoms": sorted(gained_sym),
            "lost_signs": sorted(lost_sign), "gained_signs": sorted(gained_sign),
        })


def backtest(pipe, datasets, seeds):
    report = {}
    with threadpool_limits(limits=1):
        for ds_name, cases in datasets.items():
            clean_preds = [pipe.extract(c["text"], c.get("target_subject")) for c in cases]
            report[ds_name] = {"cases": len(cases), "perturbations": {}}
            for name, (fn, is_random, desc) in PERTURBATIONS.items():
                counts, examples = blank(), []
                for case, clean in zip(cases, clean_preds):
                    for seed in range(seeds if is_random else 1):
                        run_one(pipe, case, name, fn, seed, clean, counts, examples)
                report[ds_name]["perturbations"][name] = {
                    "description": desc, "random": is_random, "counts": dict(counts), "examples": examples,
                }
    return report


def rate(num, den):
    return f"{num / den:6.1%}" if den else "   n/a"


def render(report) -> str:
    out = []
    for ds, body in report.items():
        out.append(f"\n## {ds} ({body['cases']} cases)\n")
        out.append("| perturbation | applied | lost symptom | gained symptom | lost danger sign | gained danger sign | exact-set broken | duration broken | of lost: regex-gated / rescuable |")
        out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
        for name, p in body["perturbations"].items():
            c = collections.defaultdict(int, p["counts"])
            lost = c["lost_symptom"]
            out.append(
                f"| {name} | {c['applied']} | {rate(lost, c['symptom_opportunities'])} ({lost}) | "
                f"{c['gained_symptom']} | {rate(c['lost_sign'], c['sign_opportunities'])} ({c['lost_sign']}) | "
                f"{c['gained_sign']} | {rate(c['exact_set_broken'], c['exact_set_opportunities'])} | "
                f"{rate(c['durationDays_broken'], c['durationDays_opportunities'])} | "
                f"{c['lost_not_mentioned']}/{lost} / {c['lost_rescuable']}/{lost} |"
            )
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--artifact", type=Path, default=ML / "artifacts/experimental_health_ie_final.joblib")
    ap.add_argument("--seeds", type=int, default=10, help="repetitions for each random perturbation")
    ap.add_argument("--no-synthetic", action="store_true")
    ap.add_argument("--out", type=Path, default=None, help="directory for robustness.json and robustness.md")
    args = ap.parse_args()

    if not args.artifact.is_file():
        sys.exit(f"Model artifact not found: {args.artifact}\nBuild it (see ml/README.md) or ask the owner for it.")
    pipe = ExtractionPipeline(joblib.load(args.artifact))  # trusted artifact only: joblib can run code
    report = backtest(pipe, load_datasets(not args.no_synthetic), args.seeds)
    text = render(report)
    print(text)
    if args.out:
        args.out.mkdir(parents=True, exist_ok=True)
        (args.out / "robustness.json").write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        (args.out / "robustness.md").write_text(text + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
