"""Export the verified Kilifi facility subset for the app's offline routing.

Run from the repo root after the facility data in ml/data/facilities changes:
    python3 scripts/export-facilities.py
Writes src/intake/kilifiFacilities.json. Only facilities with source-verified capability evidence are
included; a capability that is not documented stays "unknown" and is never treated as present.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ml/src"))

from verified_facility_demo import CAPABILITIES, load_subset  # noqa: E402

ANCHOR_NAME = "KILIFI DISTRICT HOSPITAL"

subset, _ = load_subset()
catalogue = json.loads((ROOT / "ml/data/facilities/catalogue.json").read_text())
anchor = next(r for r in catalogue if r["facilityName"] == ANCHOR_NAME)
lats = [r["latitude"] for r in catalogue if r["latitude"] is not None]
lons = [r["longitude"] for r in catalogue if r["longitude"] is not None]
out = {
    "source": "ml/data/facilities (ArcGIS Kilifi_Health_WFL1 snapshot + verified_capabilities.csv), accessed 2026-10-04",
    "note": "Historical public-source snapshot. Not current availability. Generated by scripts/export-facilities.py; do not edit.",
    "anchor": {"name": ANCHOR_NAME, "latitude": anchor["latitude"], "longitude": anchor["longitude"]},
    "bounds": {"south": min(lats) - 0.5, "north": max(lats) + 0.5, "west": min(lons) - 0.5, "east": max(lons) + 0.5},
    "facilities": [
        {
            "id": r["facilityId"],
            "name": r["facilityName"],
            "latitude": r["latitude"],
            "longitude": r["longitude"],
            "capabilities": {c: r["capabilities"][c] for c in sorted(CAPABILITIES)},
        }
        for r in subset
    ],
}
path = ROOT / "src/intake/kilifiFacilities.json"
path.write_text(json.dumps(out, indent=2) + "\n")
print(f"Wrote {len(out['facilities'])} facilities to {path.relative_to(ROOT)}")
